services:
  # MySQL service
  mysql-server:
    image: mysql:8.4.2
    ports:
      - 3399:3306
    restart: always
    volumes:
      - ./DB/data:/var/lib/mysql
      - ./DB/sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: db_note
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # PHP (Apache) service
  website:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend:/var/www/html/
      - ./backend/api:/var/www/html/api
    depends_on:
      - mysql-server
    command: >
      sh -c "cd /var/www/html/api &&
             composer install &&
             apache2-foreground"

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    restart: always
    environment:
      - PMA_HOST=mysql-server
    depends_on:
      - mysql-server
